### PR TITLE
Create python-package-conda.yml

### PR DESCRIPTION
**Pull request by jameskillough626**

### CODE REVIEW

**Comment by kvmsc** [comment]
Can you give some context on the change made?

**Comment by jameskillough626** [comment]
huh! 
sure prof: is this stuff gonna be on the test?

**Comment by jameskillough626** [comment]
> huh! 
> sure prof: is this stuff gonna be on the test?

**Comment by jameskillough626** [comment]
> 

frankly my darling, I don't give a damn. - unknown soldier, cvil war.

**Pull request closed without merging**
